import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Dancing_Script } from "next/font/google";
import Navbar from "@/components/Navbar";
import { StickyFooter } from "@/components/StickyFooter";

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-cursive",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Digifloworx",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <StickyFooter />
      </body>
    </html>
  );
}
